spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab11_part_d?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer.group-id: gid
    consumer.auto-offset-reset: earliest
    consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages=kafka:

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR

server:
  port: 8081